# Generated by Django 5.2.1 on 2025-08-17 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('data_source', models.CharField(default='simulated', max_length=12)),
                ('is_active', models.BooleanField(default=False)),
                ('sim_seq', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.plot')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('ph', models.FloatField(blank=True, null=True)),
                ('moisture', models.FloatField(blank=True, null=True)),
                ('n', models.FloatField(blank=True, null=True)),
                ('p', models.FloatField(blank=True, null=True)),
                ('k', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='simulated', max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.sensordevice')),
            ],
        ),
    ]
