# Generated by Django 5.2.4 on 2025-08-01 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='status',
            field=models.CharField(choices=[('planting', 'Planting'), ('growing', 'Growing'), ('harvesting', 'Harvesting'), ('closed', 'Closed')], default='planting', max_length=20),
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('yield_amount', models.FloatField()),
                ('comments', models.TextField(blank=True)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.crop')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plot', to_field='unique_plot_key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
