# Generated by Django 5.2.4 on 2025-08-20 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sensordevice_sensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='api.plot'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['plot', 'ts'], name='api_sensord_plot_id_627dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['device', 'ts'], name='api_sensord_device__45c976_idx'),
        ),
    ]
