# Generated by Django 5.2.1 on 2025-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_farm'),
        ('forum', '0003_alter_thread_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='farm_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_threads',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='forum.thread'),
        ),
    ]
