# Generated by Django 5.2.4 on 2025-08-20 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sensordata_plot_alter_sensordata_ts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordevice',
            name='linked_sensor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='source',
            field=models.CharField(default='existing_data', max_length=15),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='ts',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sensordevice',
            name='data_source',
            field=models.CharField(default='existing_data', max_length=12),
        ),
        migrations.AlterField(
            model_name='sensordevice',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.plot'),
        ),
    ]
