# Generated by Django 5.2.4 on 2025-08-20 19:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sensordevice_linked_sensor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordevice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sensordevice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordevice',
            name='data_source',
            field=models.CharField(default='existing_data', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensordevice',
            name='external_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sensordevice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensordevice',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.plot'),
        ),
        migrations.AlterUniqueTogether(
            name='sensordevice',
            unique_together={('user', 'linked_sensor_id')},
        ),
    ]
