# Generated by Django 5.2.1 on 2025-09-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sensordevice_created_at_sensordevice_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
