# Generated by Django 5.2.1 on 2025-09-30 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_crop_soil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='expected_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 30, 0, 0), null=True),
        ),
    ]
