# Generated by Django 5.2.1 on 2025-10-01 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_harvest_expected_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='api.crop'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='yield_amount',
            field=models.FloatField(default=0),
        ),
    ]
