# Generated by Django 5.2.1 on 2025-07-22 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='plot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.plot'),
        ),
    ]
