# Generated by Django 5.2.1 on 2025-07-22 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_crop_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='plot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.plot', to_field='unique_plot_key'),
        ),
    ]
