# Generated by Django 5.2.1 on 2025-10-02 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_harvest_crop_alter_harvest_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='api.crop'),
        ),
    ]
