# Generated by Django 5.2.1 on 2025-07-30 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_crop_plot'),
        ('forum', '0004_alter_chatmessage_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_threads',
        ),
        migrations.CreateModel(
            name='CustomerFavoriteThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_favorites', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.thread')),
            ],
            options={
                'db_table': 'api_customer_favorite_threads',
                'unique_together': {('customer', 'thread')},
            },
        ),
    ]
