# Generated by Django 5.2.1 on 2025-10-25 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_harvest_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_month', models.FloatField(default=0.0)),
                ('fert_month', models.FloatField(default=0.0)),
                ('harvest_days', models.IntegerField(default=0)),
                ('pest_days', models.FloatField(default=0.0)),
                ('fert_days', models.FloatField(default=0.0)),
                ('pest_total', models.FloatField(default=0.0)),
                ('fert_total', models.FloatField(default=0.0)),
                ('harvest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chemical', to='api.harvest')),
            ],
        ),
    ]
