services:
  - type: web
    name: smart-harvest-backend
    env: python
    pythonVersion: 3.13.4
    buildCommand: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt
      cd backend
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: cd backend && gunicorn backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
