# Generated by Django 5.2.1 on 2025-10-22 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0009_alter_harvest_crop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField()),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('doing', 'Doing'), ('complete', 'Complete')], default='to_do', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.harvest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
