# Generated by Django 5.2.1 on 2025-07-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_thread_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmessage',
            table='forum_chatmessage',
        ),
    ]
